cc_library(
    name = 'proto',
    srcs = [
	   'src/routersvr_config.pb.cc',
	   'src/cmd.pb.cc',
	   'src/svr_base.pb.cc',
	   'src/router.pb.cc',
	   'comm_conf.pb.cc',
    ],
	deps = [
		'//google:protobuf',
    ],
	
    # link_all_symbols = True,
)
