cc_binary(
    name = 'test',
    srcs = [
       'test.cpp',
	   'main.cpp',
	   'transaction/trans_test.cpp',
    ],
    deps = [
        '//commonlib:common',
		'//protolib:proto',
		'//hiredis_wrapper:hiredis_wrapper',
    ],
)
