// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mytest.proto

#include "mytest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace mytest {
class MysqlTestNotifyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MysqlTestNotify>
      _instance;
} _MysqlTestNotify_default_instance_;
}  // namespace mytest
namespace protobuf_mytest_2eproto {
void InitDefaultsMysqlTestNotifyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::mytest::_MysqlTestNotify_default_instance_;
    new (ptr) ::mytest::MysqlTestNotify();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mytest::MysqlTestNotify::InitAsDefaultInstance();
}

void InitDefaultsMysqlTestNotify() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMysqlTestNotifyImpl);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mytest::MysqlTestNotify, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mytest::MysqlTestNotify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::mytest::MysqlTestNotify)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::mytest::_MysqlTestNotify_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "mytest.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014mytest.proto\022\006mytest\"\021\n\017MysqlTestNotif"
      "y*\035\n\003CMD\022\026\n\021MYSQL_TEST_NOTIFY\020\350\007"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 72);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mytest.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_mytest_2eproto
namespace mytest {
const ::google::protobuf::EnumDescriptor* CMD_descriptor() {
  protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_mytest_2eproto::file_level_enum_descriptors[0];
}
bool CMD_IsValid(int value) {
  switch (value) {
    case 1000:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void MysqlTestNotify::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MysqlTestNotify::MysqlTestNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_mytest_2eproto::InitDefaultsMysqlTestNotify();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:mytest.MysqlTestNotify)
}
MysqlTestNotify::MysqlTestNotify(const MysqlTestNotify& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mytest.MysqlTestNotify)
}

void MysqlTestNotify::SharedCtor() {
  _cached_size_ = 0;
}

MysqlTestNotify::~MysqlTestNotify() {
  // @@protoc_insertion_point(destructor:mytest.MysqlTestNotify)
  SharedDtor();
}

void MysqlTestNotify::SharedDtor() {
}

void MysqlTestNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MysqlTestNotify::descriptor() {
  ::protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mytest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MysqlTestNotify& MysqlTestNotify::default_instance() {
  ::protobuf_mytest_2eproto::InitDefaultsMysqlTestNotify();
  return *internal_default_instance();
}

MysqlTestNotify* MysqlTestNotify::New(::google::protobuf::Arena* arena) const {
  MysqlTestNotify* n = new MysqlTestNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MysqlTestNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:mytest.MysqlTestNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MysqlTestNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mytest.MysqlTestNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:mytest.MysqlTestNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mytest.MysqlTestNotify)
  return false;
#undef DO_
}

void MysqlTestNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mytest.MysqlTestNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mytest.MysqlTestNotify)
}

::google::protobuf::uint8* MysqlTestNotify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mytest.MysqlTestNotify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mytest.MysqlTestNotify)
  return target;
}

size_t MysqlTestNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mytest.MysqlTestNotify)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MysqlTestNotify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mytest.MysqlTestNotify)
  GOOGLE_DCHECK_NE(&from, this);
  const MysqlTestNotify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MysqlTestNotify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mytest.MysqlTestNotify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mytest.MysqlTestNotify)
    MergeFrom(*source);
  }
}

void MysqlTestNotify::MergeFrom(const MysqlTestNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mytest.MysqlTestNotify)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void MysqlTestNotify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mytest.MysqlTestNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MysqlTestNotify::CopyFrom(const MysqlTestNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mytest.MysqlTestNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MysqlTestNotify::IsInitialized() const {
  return true;
}

void MysqlTestNotify::Swap(MysqlTestNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MysqlTestNotify::InternalSwap(MysqlTestNotify* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MysqlTestNotify::GetMetadata() const {
  protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mytest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mytest

// @@protoc_insertion_point(global_scope)
