// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcm.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Host struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	InnerIp              *string  `protobuf:"bytes,2,opt,name=inner_ip,json=innerIp" json:"inner_ip,omitempty"`
	OuterIp              *string  `protobuf:"bytes,3,opt,name=outer_ip,json=outerIp" json:"outer_ip,omitempty"`
	DeployIp             *string  `protobuf:"bytes,4,opt,name=deploy_ip,json=deployIp" json:"deploy_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Host) GetInnerIp() string {
	if m != nil && m.InnerIp != nil {
		return *m.InnerIp
	}
	return ""
}

func (m *Host) GetOuterIp() string {
	if m != nil && m.OuterIp != nil {
		return *m.OuterIp
	}
	return ""
}

func (m *Host) GetDeployIp() string {
	if m != nil && m.DeployIp != nil {
		return *m.DeployIp
	}
	return ""
}

type HostCfg struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostCfg) Reset()         { *m = HostCfg{} }
func (m *HostCfg) String() string { return proto.CompactTextString(m) }
func (*HostCfg) ProtoMessage()    {}
func (*HostCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{1}
}

func (m *HostCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostCfg.Unmarshal(m, b)
}
func (m *HostCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostCfg.Marshal(b, m, deterministic)
}
func (m *HostCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostCfg.Merge(m, src)
}
func (m *HostCfg) XXX_Size() int {
	return xxx_messageInfo_HostCfg.Size(m)
}
func (m *HostCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_HostCfg.DiscardUnknown(m)
}

var xxx_messageInfo_HostCfg proto.InternalMessageInfo

func (m *HostCfg) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ArtifactFile struct {
	Src                  *string  `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	Dst                  *string  `protobuf:"bytes,2,opt,name=dst" json:"dst,omitempty"`
	IsDir                *bool    `protobuf:"varint,3,opt,name=is_dir,json=isDir" json:"is_dir,omitempty"`
	NeedBackup           *bool    `protobuf:"varint,4,opt,name=need_backup,json=needBackup" json:"need_backup,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtifactFile) Reset()         { *m = ArtifactFile{} }
func (m *ArtifactFile) String() string { return proto.CompactTextString(m) }
func (*ArtifactFile) ProtoMessage()    {}
func (*ArtifactFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{2}
}

func (m *ArtifactFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactFile.Unmarshal(m, b)
}
func (m *ArtifactFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactFile.Marshal(b, m, deterministic)
}
func (m *ArtifactFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactFile.Merge(m, src)
}
func (m *ArtifactFile) XXX_Size() int {
	return xxx_messageInfo_ArtifactFile.Size(m)
}
func (m *ArtifactFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactFile.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactFile proto.InternalMessageInfo

func (m *ArtifactFile) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *ArtifactFile) GetDst() string {
	if m != nil && m.Dst != nil {
		return *m.Dst
	}
	return ""
}

func (m *ArtifactFile) GetIsDir() bool {
	if m != nil && m.IsDir != nil {
		return *m.IsDir
	}
	return false
}

func (m *ArtifactFile) GetNeedBackup() bool {
	if m != nil && m.NeedBackup != nil {
		return *m.NeedBackup
	}
	return false
}

func (m *ArtifactFile) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AgentArtifact struct {
	Files                []*ArtifactFile `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	Name                 *string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	FunctionId           *int32          `protobuf:"varint,3,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	StartCmd             *string         `protobuf:"bytes,4,opt,name=start_cmd,json=startCmd" json:"start_cmd,omitempty"`
	StopCmd              *string         `protobuf:"bytes,5,opt,name=stop_cmd,json=stopCmd" json:"stop_cmd,omitempty"`
	CleanCmd             *string         `protobuf:"bytes,6,opt,name=clean_cmd,json=cleanCmd" json:"clean_cmd,omitempty"`
	CheckCmd             *string         `protobuf:"bytes,7,opt,name=check_cmd,json=checkCmd" json:"check_cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AgentArtifact) Reset()         { *m = AgentArtifact{} }
func (m *AgentArtifact) String() string { return proto.CompactTextString(m) }
func (*AgentArtifact) ProtoMessage()    {}
func (*AgentArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{3}
}

func (m *AgentArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentArtifact.Unmarshal(m, b)
}
func (m *AgentArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentArtifact.Marshal(b, m, deterministic)
}
func (m *AgentArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentArtifact.Merge(m, src)
}
func (m *AgentArtifact) XXX_Size() int {
	return xxx_messageInfo_AgentArtifact.Size(m)
}
func (m *AgentArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_AgentArtifact proto.InternalMessageInfo

func (m *AgentArtifact) GetFiles() []*ArtifactFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *AgentArtifact) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AgentArtifact) GetFunctionId() int32 {
	if m != nil && m.FunctionId != nil {
		return *m.FunctionId
	}
	return 0
}

func (m *AgentArtifact) GetStartCmd() string {
	if m != nil && m.StartCmd != nil {
		return *m.StartCmd
	}
	return ""
}

func (m *AgentArtifact) GetStopCmd() string {
	if m != nil && m.StopCmd != nil {
		return *m.StopCmd
	}
	return ""
}

func (m *AgentArtifact) GetCleanCmd() string {
	if m != nil && m.CleanCmd != nil {
		return *m.CleanCmd
	}
	return ""
}

func (m *AgentArtifact) GetCheckCmd() string {
	if m != nil && m.CheckCmd != nil {
		return *m.CheckCmd
	}
	return ""
}

type TemplateArtifactItem struct {
	TemplateName         *string         `protobuf:"bytes,1,opt,name=template_name,json=templateName" json:"template_name,omitempty"`
	Files                []*ArtifactFile `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TemplateArtifactItem) Reset()         { *m = TemplateArtifactItem{} }
func (m *TemplateArtifactItem) String() string { return proto.CompactTextString(m) }
func (*TemplateArtifactItem) ProtoMessage()    {}
func (*TemplateArtifactItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{4}
}

func (m *TemplateArtifactItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateArtifactItem.Unmarshal(m, b)
}
func (m *TemplateArtifactItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateArtifactItem.Marshal(b, m, deterministic)
}
func (m *TemplateArtifactItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateArtifactItem.Merge(m, src)
}
func (m *TemplateArtifactItem) XXX_Size() int {
	return xxx_messageInfo_TemplateArtifactItem.Size(m)
}
func (m *TemplateArtifactItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateArtifactItem.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateArtifactItem proto.InternalMessageInfo

func (m *TemplateArtifactItem) GetTemplateName() string {
	if m != nil && m.TemplateName != nil {
		return *m.TemplateName
	}
	return ""
}

func (m *TemplateArtifactItem) GetFiles() []*ArtifactFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type TemplateArtifact struct {
	TemplateArtifacts    []*TemplateArtifactItem `protobuf:"bytes,1,rep,name=template_artifacts,json=templateArtifacts" json:"template_artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TemplateArtifact) Reset()         { *m = TemplateArtifact{} }
func (m *TemplateArtifact) String() string { return proto.CompactTextString(m) }
func (*TemplateArtifact) ProtoMessage()    {}
func (*TemplateArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{5}
}

func (m *TemplateArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateArtifact.Unmarshal(m, b)
}
func (m *TemplateArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateArtifact.Marshal(b, m, deterministic)
}
func (m *TemplateArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateArtifact.Merge(m, src)
}
func (m *TemplateArtifact) XXX_Size() int {
	return xxx_messageInfo_TemplateArtifact.Size(m)
}
func (m *TemplateArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateArtifact proto.InternalMessageInfo

func (m *TemplateArtifact) GetTemplateArtifacts() []*TemplateArtifactItem {
	if m != nil {
		return m.TemplateArtifacts
	}
	return nil
}

type NormalArtifactItem struct {
	TemplateName         *string         `protobuf:"bytes,1,opt,name=template_name,json=templateName" json:"template_name,omitempty"`
	Name                 *string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	FunctionId           *int32          `protobuf:"varint,3,opt,name=function_id,json=functionId" json:"function_id,omitempty"`
	StartPriority        *int32          `protobuf:"varint,4,opt,name=start_priority,json=startPriority" json:"start_priority,omitempty"`
	Files                []*ArtifactFile `protobuf:"bytes,5,rep,name=files" json:"files,omitempty"`
	Copies               *uint32         `protobuf:"varint,6,opt,name=copies,def=1" json:"copies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NormalArtifactItem) Reset()         { *m = NormalArtifactItem{} }
func (m *NormalArtifactItem) String() string { return proto.CompactTextString(m) }
func (*NormalArtifactItem) ProtoMessage()    {}
func (*NormalArtifactItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{6}
}

func (m *NormalArtifactItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalArtifactItem.Unmarshal(m, b)
}
func (m *NormalArtifactItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalArtifactItem.Marshal(b, m, deterministic)
}
func (m *NormalArtifactItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalArtifactItem.Merge(m, src)
}
func (m *NormalArtifactItem) XXX_Size() int {
	return xxx_messageInfo_NormalArtifactItem.Size(m)
}
func (m *NormalArtifactItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalArtifactItem.DiscardUnknown(m)
}

var xxx_messageInfo_NormalArtifactItem proto.InternalMessageInfo

const Default_NormalArtifactItem_Copies uint32 = 1

func (m *NormalArtifactItem) GetTemplateName() string {
	if m != nil && m.TemplateName != nil {
		return *m.TemplateName
	}
	return ""
}

func (m *NormalArtifactItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NormalArtifactItem) GetFunctionId() int32 {
	if m != nil && m.FunctionId != nil {
		return *m.FunctionId
	}
	return 0
}

func (m *NormalArtifactItem) GetStartPriority() int32 {
	if m != nil && m.StartPriority != nil {
		return *m.StartPriority
	}
	return 0
}

func (m *NormalArtifactItem) GetFiles() []*ArtifactFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *NormalArtifactItem) GetCopies() uint32 {
	if m != nil && m.Copies != nil {
		return *m.Copies
	}
	return Default_NormalArtifactItem_Copies
}

type NormalArtifact struct {
	Artifacts            []*NormalArtifactItem `protobuf:"bytes,1,rep,name=artifacts" json:"artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NormalArtifact) Reset()         { *m = NormalArtifact{} }
func (m *NormalArtifact) String() string { return proto.CompactTextString(m) }
func (*NormalArtifact) ProtoMessage()    {}
func (*NormalArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{7}
}

func (m *NormalArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalArtifact.Unmarshal(m, b)
}
func (m *NormalArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalArtifact.Marshal(b, m, deterministic)
}
func (m *NormalArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalArtifact.Merge(m, src)
}
func (m *NormalArtifact) XXX_Size() int {
	return xxx_messageInfo_NormalArtifact.Size(m)
}
func (m *NormalArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_NormalArtifact proto.InternalMessageInfo

func (m *NormalArtifact) GetArtifacts() []*NormalArtifactItem {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

type ArtifactGroupItem struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ArtifactNames        []string `protobuf:"bytes,2,rep,name=artifact_names,json=artifactNames" json:"artifact_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtifactGroupItem) Reset()         { *m = ArtifactGroupItem{} }
func (m *ArtifactGroupItem) String() string { return proto.CompactTextString(m) }
func (*ArtifactGroupItem) ProtoMessage()    {}
func (*ArtifactGroupItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{8}
}

func (m *ArtifactGroupItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactGroupItem.Unmarshal(m, b)
}
func (m *ArtifactGroupItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactGroupItem.Marshal(b, m, deterministic)
}
func (m *ArtifactGroupItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactGroupItem.Merge(m, src)
}
func (m *ArtifactGroupItem) XXX_Size() int {
	return xxx_messageInfo_ArtifactGroupItem.Size(m)
}
func (m *ArtifactGroupItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactGroupItem.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactGroupItem proto.InternalMessageInfo

func (m *ArtifactGroupItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ArtifactGroupItem) GetArtifactNames() []string {
	if m != nil {
		return m.ArtifactNames
	}
	return nil
}

type ArtifactGroup struct {
	ArtifactGroups       []*ArtifactGroupItem `protobuf:"bytes,1,rep,name=artifact_groups,json=artifactGroups" json:"artifact_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ArtifactGroup) Reset()         { *m = ArtifactGroup{} }
func (m *ArtifactGroup) String() string { return proto.CompactTextString(m) }
func (*ArtifactGroup) ProtoMessage()    {}
func (*ArtifactGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{9}
}

func (m *ArtifactGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactGroup.Unmarshal(m, b)
}
func (m *ArtifactGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactGroup.Marshal(b, m, deterministic)
}
func (m *ArtifactGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactGroup.Merge(m, src)
}
func (m *ArtifactGroup) XXX_Size() int {
	return xxx_messageInfo_ArtifactGroup.Size(m)
}
func (m *ArtifactGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactGroup proto.InternalMessageInfo

func (m *ArtifactGroup) GetArtifactGroups() []*ArtifactGroupItem {
	if m != nil {
		return m.ArtifactGroups
	}
	return nil
}

type KeyValue struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{10}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type InstanceGroup struct {
	ArtifactGroupName    *string  `protobuf:"bytes,1,opt,name=artifact_group_name,json=artifactGroupName" json:"artifact_group_name,omitempty"`
	HostName             *string  `protobuf:"bytes,2,opt,name=host_name,json=hostName" json:"host_name,omitempty"`
	InstanceId           *int32   `protobuf:"varint,3,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGroup) Reset()         { *m = InstanceGroup{} }
func (m *InstanceGroup) String() string { return proto.CompactTextString(m) }
func (*InstanceGroup) ProtoMessage()    {}
func (*InstanceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{11}
}

func (m *InstanceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroup.Unmarshal(m, b)
}
func (m *InstanceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroup.Marshal(b, m, deterministic)
}
func (m *InstanceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroup.Merge(m, src)
}
func (m *InstanceGroup) XXX_Size() int {
	return xxx_messageInfo_InstanceGroup.Size(m)
}
func (m *InstanceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroup proto.InternalMessageInfo

func (m *InstanceGroup) GetArtifactGroupName() string {
	if m != nil && m.ArtifactGroupName != nil {
		return *m.ArtifactGroupName
	}
	return ""
}

func (m *InstanceGroup) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

func (m *InstanceGroup) GetInstanceId() int32 {
	if m != nil && m.InstanceId != nil {
		return *m.InstanceId
	}
	return 0
}

type Zone struct {
	Name                 *string          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id                   *int32           `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	InstanceGroups       []*InstanceGroup `protobuf:"bytes,4,rep,name=instance_groups,json=instanceGroups" json:"instance_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{12}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Zone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Zone) GetInstanceGroups() []*InstanceGroup {
	if m != nil {
		return m.InstanceGroups
	}
	return nil
}

type World struct {
	Name                 *string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id                   *int32      `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	User                 *string     `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Passwd               *string     `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
	Variables            []*KeyValue `protobuf:"bytes,5,rep,name=variables" json:"variables,omitempty"`
	Zones                []*Zone     `protobuf:"bytes,6,rep,name=zones" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *World) Reset()         { *m = World{} }
func (m *World) String() string { return proto.CompactTextString(m) }
func (*World) ProtoMessage()    {}
func (*World) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{13}
}

func (m *World) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_World.Unmarshal(m, b)
}
func (m *World) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_World.Marshal(b, m, deterministic)
}
func (m *World) XXX_Merge(src proto.Message) {
	xxx_messageInfo_World.Merge(m, src)
}
func (m *World) XXX_Size() int {
	return xxx_messageInfo_World.Size(m)
}
func (m *World) XXX_DiscardUnknown() {
	xxx_messageInfo_World.DiscardUnknown(m)
}

var xxx_messageInfo_World proto.InternalMessageInfo

func (m *World) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *World) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *World) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *World) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *World) GetVariables() []*KeyValue {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *World) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

type DeployInfo struct {
	TmpRootPath          *string  `protobuf:"bytes,2,opt,name=tmp_root_path,json=tmpRootPath" json:"tmp_root_path,omitempty"`
	DstRootPath          *string  `protobuf:"bytes,3,opt,name=dst_root_path,json=dstRootPath" json:"dst_root_path,omitempty"`
	ListenPort           *int32   `protobuf:"varint,4,opt,name=listen_port,json=listenPort" json:"listen_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{14}
}

func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (m *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(m, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetTmpRootPath() string {
	if m != nil && m.TmpRootPath != nil {
		return *m.TmpRootPath
	}
	return ""
}

func (m *DeployInfo) GetDstRootPath() string {
	if m != nil && m.DstRootPath != nil {
		return *m.DstRootPath
	}
	return ""
}

func (m *DeployInfo) GetListenPort() int32 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

type Deploy struct {
	TmpRootPath          *string     `protobuf:"bytes,2,opt,name=tmp_root_path,json=tmpRootPath" json:"tmp_root_path,omitempty"`
	DstRootPath          *string     `protobuf:"bytes,3,opt,name=dst_root_path,json=dstRootPath" json:"dst_root_path,omitempty"`
	Variables            []*KeyValue `protobuf:"bytes,4,rep,name=variables" json:"variables,omitempty"`
	Worlds               []*World    `protobuf:"bytes,5,rep,name=worlds" json:"worlds,omitempty"`
	ListenPort           *int32      `protobuf:"varint,6,opt,name=listen_port,json=listenPort" json:"listen_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Deploy) Reset()         { *m = Deploy{} }
func (m *Deploy) String() string { return proto.CompactTextString(m) }
func (*Deploy) ProtoMessage()    {}
func (*Deploy) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{15}
}

func (m *Deploy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy.Unmarshal(m, b)
}
func (m *Deploy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy.Marshal(b, m, deterministic)
}
func (m *Deploy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy.Merge(m, src)
}
func (m *Deploy) XXX_Size() int {
	return xxx_messageInfo_Deploy.Size(m)
}
func (m *Deploy) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy proto.InternalMessageInfo

func (m *Deploy) GetTmpRootPath() string {
	if m != nil && m.TmpRootPath != nil {
		return *m.TmpRootPath
	}
	return ""
}

func (m *Deploy) GetDstRootPath() string {
	if m != nil && m.DstRootPath != nil {
		return *m.DstRootPath
	}
	return ""
}

func (m *Deploy) GetVariables() []*KeyValue {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *Deploy) GetWorlds() []*World {
	if m != nil {
		return m.Worlds
	}
	return nil
}

func (m *Deploy) GetListenPort() int32 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func init() {
	proto.RegisterType((*Host)(nil), "protocol.Host")
	proto.RegisterType((*HostCfg)(nil), "protocol.HostCfg")
	proto.RegisterType((*ArtifactFile)(nil), "protocol.ArtifactFile")
	proto.RegisterType((*AgentArtifact)(nil), "protocol.AgentArtifact")
	proto.RegisterType((*TemplateArtifactItem)(nil), "protocol.TemplateArtifactItem")
	proto.RegisterType((*TemplateArtifact)(nil), "protocol.TemplateArtifact")
	proto.RegisterType((*NormalArtifactItem)(nil), "protocol.NormalArtifactItem")
	proto.RegisterType((*NormalArtifact)(nil), "protocol.NormalArtifact")
	proto.RegisterType((*ArtifactGroupItem)(nil), "protocol.ArtifactGroupItem")
	proto.RegisterType((*ArtifactGroup)(nil), "protocol.ArtifactGroup")
	proto.RegisterType((*KeyValue)(nil), "protocol.KeyValue")
	proto.RegisterType((*InstanceGroup)(nil), "protocol.InstanceGroup")
	proto.RegisterType((*Zone)(nil), "protocol.Zone")
	proto.RegisterType((*World)(nil), "protocol.World")
	proto.RegisterType((*DeployInfo)(nil), "protocol.DeployInfo")
	proto.RegisterType((*Deploy)(nil), "protocol.Deploy")
}

func init() { proto.RegisterFile("gcm.proto", fileDescriptor_6e49f9b792356f6b) }

var fileDescriptor_6e49f9b792356f6b = []byte{
	// 813 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0xd6, 0xa4, 0x99, 0x34, 0x73, 0xb2, 0x93, 0x6e, 0xcd, 0xb2, 0x74, 0x55, 0x44, 0x2b, 0xc3,
	0x8a, 0xbd, 0x40, 0x05, 0xf6, 0x72, 0xaf, 0x58, 0x5a, 0x01, 0x11, 0x50, 0x55, 0x16, 0x3f, 0x12,
	0x37, 0x23, 0xef, 0x8c, 0x93, 0x5a, 0x9d, 0x19, 0x5b, 0xb6, 0xb3, 0xab, 0x20, 0xc1, 0x2b, 0xf1,
	0x22, 0x3c, 0x03, 0x57, 0x3c, 0x08, 0xf2, 0xdf, 0xcc, 0x24, 0xdb, 0x8b, 0x80, 0xb8, 0xaa, 0xfd,
	0x7d, 0x67, 0x7c, 0xbe, 0xf3, 0x9d, 0xd3, 0x13, 0xc8, 0x56, 0x65, 0x73, 0x21, 0x95, 0x30, 0x02,
	0x4d, 0xdd, 0x9f, 0x52, 0xd4, 0xb8, 0x81, 0xf1, 0x37, 0x42, 0x1b, 0x84, 0x60, 0xdc, 0xd2, 0x86,
	0x9d, 0x24, 0xe7, 0xc9, 0xb3, 0x8c, 0xb8, 0x33, 0x7a, 0x02, 0x53, 0xde, 0xb6, 0x4c, 0x15, 0x5c,
	0x9e, 0x8c, 0x1c, 0x7e, 0xe8, 0xee, 0x0b, 0x69, 0x29, 0xb1, 0x36, 0x9e, 0x3a, 0xf0, 0x94, 0xbb,
	0x2f, 0x24, 0x3a, 0x85, 0xac, 0x62, 0xb2, 0x16, 0x1b, 0xcb, 0x8d, 0x1d, 0x37, 0xf5, 0xc0, 0x42,
	0xe2, 0x4f, 0xe1, 0xd0, 0xa6, 0xbb, 0x5c, 0xae, 0xd0, 0x47, 0x90, 0xde, 0x0a, 0x6d, 0xf4, 0x49,
	0x72, 0x7e, 0xf0, 0x6c, 0xf6, 0x7c, 0x7e, 0x11, 0x35, 0x5d, 0xd8, 0x08, 0xe2, 0x49, 0xfc, 0x3b,
	0x3c, 0x78, 0xa9, 0x0c, 0x5f, 0xd2, 0xd2, 0x7c, 0xc5, 0x6b, 0x86, 0x1e, 0xc2, 0x81, 0x56, 0x65,
	0x90, 0x69, 0x8f, 0x16, 0xa9, 0xb4, 0x09, 0x02, 0xed, 0x11, 0xbd, 0x0b, 0x13, 0xae, 0x8b, 0x8a,
	0x2b, 0x27, 0x6d, 0x4a, 0x52, 0xae, 0xaf, 0xb8, 0x42, 0x67, 0x30, 0x6b, 0x19, 0xab, 0x8a, 0x57,
	0xb4, 0xbc, 0x5b, 0x7b, 0x69, 0x53, 0x02, 0x16, 0xfa, 0xd2, 0x21, 0xd6, 0x03, 0x43, 0x57, 0xfa,
	0x24, 0x3d, 0x3f, 0xb0, 0x1e, 0xd8, 0x33, 0xfe, 0x3b, 0x81, 0xfc, 0xe5, 0x8a, 0xb5, 0x26, 0xaa,
	0x40, 0x9f, 0x40, 0xba, 0xe4, 0x35, 0x8b, 0xba, 0x1f, 0xf7, 0xba, 0x87, 0x42, 0x89, 0x0f, 0xea,
	0x7c, 0x1d, 0x0d, 0x7c, 0x3d, 0x83, 0xd9, 0x72, 0xdd, 0x96, 0x86, 0x8b, 0xb6, 0xe0, 0x95, 0x13,
	0x99, 0x12, 0x88, 0xd0, 0xa2, 0xb2, 0x16, 0x6a, 0x43, 0x95, 0x29, 0xca, 0xa6, 0x8a, 0x16, 0x3a,
	0xe0, 0xb2, 0xa9, 0xac, 0xf5, 0xda, 0x08, 0xe9, 0xb8, 0xd4, 0x5b, 0x6f, 0xef, 0x96, 0x3a, 0x85,
	0xac, 0xac, 0x19, 0x6d, 0x1d, 0x37, 0xf1, 0xdf, 0x39, 0x20, 0x92, 0xb7, 0xac, 0xbc, 0x73, 0xe4,
	0x61, 0x20, 0x2d, 0x70, 0xd9, 0x54, 0x98, 0xc3, 0xa3, 0x1f, 0x58, 0x23, 0x6b, 0x6a, 0x58, 0xac,
	0x62, 0x61, 0x58, 0x83, 0x3e, 0x84, 0xdc, 0x04, 0xbc, 0x18, 0xcc, 0xc7, 0x83, 0x08, 0x5e, 0xdb,
	0x7a, 0x3a, 0x47, 0x46, 0x7b, 0x38, 0x82, 0x29, 0x3c, 0xdc, 0x4d, 0x85, 0xbe, 0x07, 0xd4, 0xa5,
	0xa1, 0x01, 0x8c, 0x06, 0x7f, 0xd0, 0x3f, 0x77, 0x9f, 0x44, 0x72, 0x6c, 0x76, 0x50, 0x8d, 0xff,
	0x4a, 0x00, 0x5d, 0x0b, 0xd5, 0xd0, 0xfa, 0xdf, 0x17, 0xf3, 0x9f, 0x1a, 0xf6, 0x14, 0xe6, 0xbe,
	0x61, 0x52, 0x71, 0xa1, 0xb8, 0xd9, 0xb8, 0xae, 0xa5, 0x24, 0x77, 0xe8, 0x4d, 0x00, 0x7b, 0xa3,
	0xd2, 0x7d, 0x46, 0xe7, 0x09, 0x4c, 0x4a, 0x21, 0x39, 0xd3, 0xae, 0x95, 0xf9, 0x8b, 0xe4, 0x73,
	0x12, 0x00, 0xfc, 0x1d, 0xcc, 0xb7, 0xeb, 0x43, 0x2f, 0x20, 0xdb, 0x35, 0xee, 0xfd, 0xfe, 0xf9,
	0xb7, 0xcd, 0x20, 0x7d, 0x38, 0xbe, 0x86, 0xe3, 0x48, 0x7d, 0xad, 0xc4, 0x5a, 0x3a, 0xb3, 0xee,
	0x5b, 0x08, 0x4f, 0x61, 0x1e, 0xbf, 0x72, 0x06, 0xfa, 0x8e, 0x67, 0x24, 0x8f, 0xa8, 0x75, 0x50,
	0xe3, 0x1f, 0x21, 0xdf, 0x7a, 0x0f, 0x5d, 0xc1, 0x51, 0xf7, 0xdd, 0xca, 0x22, 0x51, 0xe2, 0xe9,
	0xdb, 0x0e, 0x74, 0x0a, 0x48, 0x97, 0xcb, 0x41, 0x1a, 0x3f, 0x87, 0xe9, 0xb7, 0x6c, 0xf3, 0x13,
	0xad, 0xd7, 0x6e, 0x0d, 0xdc, 0xb1, 0x4d, 0x5c, 0x03, 0x77, 0x6c, 0x83, 0x1e, 0x41, 0xfa, 0xda,
	0x52, 0xa1, 0x71, 0xfe, 0x82, 0x7f, 0x83, 0x7c, 0xd1, 0x6a, 0x43, 0xdb, 0x92, 0x79, 0x29, 0x17,
	0xf0, 0xce, 0xb6, 0x94, 0xe1, 0x24, 0x1c, 0x6f, 0x65, 0x74, 0xe3, 0x70, 0x0a, 0x99, 0x5d, 0x44,
	0xc5, 0x60, 0x26, 0xa6, 0x16, 0xb8, 0x0e, 0x73, 0xc1, 0xc3, 0xeb, 0x83, 0xb9, 0x88, 0xd0, 0xa2,
	0xc2, 0x35, 0x8c, 0x7f, 0x11, 0x2d, 0xbb, 0xd7, 0xcc, 0x39, 0x8c, 0x78, 0xe5, 0x9e, 0x4c, 0xc9,
	0x88, 0x57, 0xe8, 0x0b, 0x38, 0xea, 0x1e, 0x0b, 0x26, 0x8d, 0x9d, 0x49, 0xef, 0xf5, 0x26, 0x6d,
	0xd5, 0x42, 0xe6, 0x7c, 0x78, 0xd5, 0xf8, 0x8f, 0x04, 0xd2, 0x9f, 0x85, 0xaa, 0xab, 0xbd, 0xf2,
	0x21, 0x18, 0xaf, 0x35, 0x53, 0x61, 0x7d, 0xbb, 0x33, 0x7a, 0x0c, 0x13, 0x49, 0xb5, 0x7e, 0x13,
	0xb7, 0x4e, 0xb8, 0xa1, 0xcf, 0x20, 0x7b, 0x4d, 0x15, 0xa7, 0xaf, 0xfa, 0xe1, 0x45, 0xbd, 0xaa,
	0xd8, 0x15, 0xd2, 0x07, 0xd9, 0xed, 0xfe, 0xab, 0x68, 0xdd, 0xec, 0xee, 0x6c, 0x77, 0x6b, 0x08,
	0xf1, 0x24, 0x5e, 0x03, 0x5c, 0xf9, 0x9f, 0x86, 0x76, 0x29, 0x10, 0x86, 0xdc, 0x34, 0xb2, 0x50,
	0x42, 0x98, 0x42, 0x52, 0x73, 0x1b, 0xfc, 0x9e, 0x99, 0x46, 0x12, 0x21, 0xcc, 0x0d, 0x35, 0xb7,
	0x36, 0xa6, 0xd2, 0x66, 0x10, 0xe3, 0xe5, 0xcf, 0x2a, 0x6d, 0xba, 0x98, 0x33, 0x98, 0xd5, 0x5c,
	0x1b, 0xd6, 0x16, 0x52, 0x28, 0x13, 0xfe, 0x15, 0xc1, 0x43, 0x37, 0x42, 0x19, 0xfc, 0x67, 0x02,
	0x13, 0x9f, 0xf7, 0x7f, 0xcb, 0xb9, 0xe5, 0xd0, 0x78, 0x1f, 0x87, 0x3e, 0x86, 0xc9, 0x1b, 0xdb,
	0xac, 0x68, 0xe8, 0x51, 0x1f, 0xee, 0x9a, 0x48, 0x02, 0xbd, 0x5b, 0xce, 0x64, 0xb7, 0x9c, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x85, 0x77, 0xb1, 0x01, 0xd9, 0x07, 0x00, 0x00,
}
