
#proto_library(
#)

cc_library(
    name = 'tinyxml',
    srcs = [
	   'tinyxml/tinystr.cpp',
	   'tinyxml/tinyxml.cpp',
	   'tinyxml/tinyxmlerror.cpp',
	   'tinyxml/tinyxmlparser.cpp',
    ],

    deps = [
    ],

    #link_all_symbols = True,
)


