
#proto_library(
#)

cc_library(
    name = 'tinyxml',
    srcs = [
	   'tinystr.cpp',
	   'tinyxml.cpp',
	   'tinyxmlerror.cpp',
	   'tinyxmlparser.cpp',
    ],

    deps = [
    ],

    #link_all_symbols = True,
)


