cc_binary(
    name = 'dbtool',
    srcs = [
       'main.cpp',
	   'dbtool.pb.cc',
    ],
    deps = [
		'//google:protobuf',
        '//commonlib:common',
		'//slience:slience',
		'//mysqlclient:mysqlclient'
    ],
)
